# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/profiles/qemu-guest.nix")
    ];

  boot = {
    initrd = {
      availableKernelModules = [
        "ata_piix"
        "uhci_hcd"
        "virtio_pci"
        "sr_mod"
        "virtio_blk"
        "cryptd"
      ];
      kernelModules = [ "dm-snapshot" ];
      supportedFilesystems = [ "btrfs" ];
    };
    supportedFilesystems = [ "btrfs" ];
    kernelModules = [ ];
    extraModulePackages = [ ];
  };

  powerManagement.cpuFreqGovernor = "performance";

  swapDevices = [ ];

  zramSwap.enable = true;
}
