#!/usr/bin/env zsh

set -x

export MONITORS=( $(xrandr -q | grep ' connected' | cut -d' ' -f1) )

if [[ $(hostname) == 'purple' ]]; then
    if [ ${#MONITORS[@]} -eq 2 ]; then
        xrandr --output DP-0 --pos 0x1440 --primary
        xrandr --output HDMI-0 --pos 200x0 --auto
        # set workspaces
        bspc monitor DP-0 -d {Main,Dev,Pass,Music,Messaging,Mail,Notes,Editing,Recording,Aux}
        bspc monitor HDMI-0 -d Other
    else
        xrandr --output ${MONITORS[1]}
        bspc monitor ${MONITORS[1]} -d {Main,Dev,Pass,Music,Messaging,Mail,Notes,Editing,Recording,Aux}
    fi
else
    xrandr --auto
    bspc monitor ${MONITORS[1]} -d {I,II,III,IV,V,VI,VII,VIII,IX,X}
fi

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

# Rules
bspc rule -r '*'

bspc rule -a xst-256color state=floating

# source rc files
for file in $XDG_CONFIG_HOME/bspwm/rc.d/*; do
  source "$file"
done

feh --bg-center $DOTFILES/modules/themes/quack/config/wallpaper.png

# workaround to autostart a couple daemons
if ! pgrep mullvad > /dev/null; then
    command -v mullvad >/dev/null && mullvad connect &
fi

if ! pgrep greenclip > /dev/null; then
    greenclip daemon >/dev/null &
fi

if ! pgrep udiskie > /dev/null; then
    udiskie --tray -aF &
fi

# Autostart scc-daemon for a working Steam controller
scc-daemon start
