#!/usr/bin/env zsh

set -x

export MONITORS=( $(xrandr -q | grep ' connected' | cut -d' ' -f1) )

if [[ $(hostname) == 'purple' ]]; then
    if [ ${#MONITORS[@]} -eq 2 ]; then
        xrandr --output ${MONITORS[1]} --primary --below ${MONITORS[2]}
        # set workspaces
        bspc monitor ${MONITORS[1]} -d {Main,Dev,Pass,Music,Messaging,Editing,Browsing,Recording,Notes}
        bspc monitor ${MONITORS[2]} -d {VMs}
    else
        xrandr --output ${MONITORS[1]}
        bspc monitor ${MONITORS[1]} -d {Main,Dev,Pass,Music,Messaging,Editing,Browsing,Recording}
    fi
else
    xrandr --auto
    bspc monitor ${MONITORS[1]} -d {1,2,3,4}
fi

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

# Rules
bspc rule -r '*'

bspc rule -a xst-256color state=floating
bspc rule -a Firefox desktop='^1'
bspc rule -a kitty desktop='^1'
bspc rule -a codium desktop='^2'
bspc rule -a KeePassXC desktop='^3'
bspc rule -a musikcube desktop='^4'
bspc rule -a signal-desktop desktop='^5'
bspc rule -a telegram-desktop desktop='^5'
bspc rule -a gimp desktop='^6'
bspc rule -a obs desktop='^8'

# workaround to autostart mullvad-vpn
command -v mullvad-vpn >/dev/null && mullvad-vpn
