#!/usr/bin/env zsh

set -x

export MONITORS=( $(xrandr -q | grep ' connected' | cut -d' ' -f1) )

if [[ $(hostname) == 'purple' ]]; then
    xrandr --output ${MONITORS[1]} --primary --below ${MONITORS[2]}
    # set workspaces
    bspc monitor ${MONITORS[1]} -d {1,2,5,6}
    bspc monitor ${MONITORS[2]} -d {3,4,7,8}
else
    xrandr --auto
    bspc monitor ${MONITORS[1]} -d {1,2,3,4}
fi

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

# Rules
bspc rule -r '*'

for file in $XDG_CONFIG_HOME/bspwm/rc.d/*; do
  source "$file"
done

# workaround to autostart mullvad-vpn
command -v mullvad-vpn >/dev/null && mullvad-vpn

# same for nextlcoud-client
command -v nextcloud >/dev/null && nextcloud

sleep 30

# workaround until nfancurve works
notify-send 'Set GPU fan speed!'
