#! /nix/store/4l7wsi6h6283194r6fqy1731qxlagq62-bash-4.4-p23/bin/bash -e
export PATH='/nix/store/ypz0spir3lils9m89416byz8v7chf7k8-w3m-0.5.3+git20190105/bin:/nix/store/i4hb5b4vnz88g3rwzf9pfqs2125lr0z3-dante-1.4.2/bin'${PATH:+':'}$PATH
exec -a "$0" "/nix/store/xf6rsf6xlqiqk8nbcqcnf3xkam56g66f-aerc-0.4.0/share/aerc/filters/.html-wrapped"  "$@"
