if [ ! -d "$ZGENOM_DIR" ]; then
  if nc -zw1 ifconfig.me 443; then
    git clone https://github.com/jandamm/zgenom.git "$ZGENOM_DIR"
  else
    echo "No internet connectivity. Cannot initialize zgenom"
    exit 1
  fi
fi

export ZSH_TAB_TITLE_DEFAULT_DISABLE_PREFIX=true
export ZSH_TAB_TITLE_ONLY_FOLDER=true
export ZSH_TAB_TITLE_CONCAT_FOLDER_PROCESS=true

source $ZGENOM_SOURCE
if ! zgenom saved; then
  echo "Initializing zgenom"
  zgenom load hlissner/zsh-autopair autopair.zsh
  zgenom load zsh-users/zsh-history-substring-search
  zgenom load totoroot/history-search-multi-word
  zgenom load zsh-users/zsh-completions src
  zgenom load junegunn/fzf shell
  zgenom load trystan2k/zsh-tab-title
  zgenom load chisui/zsh-nix-shell
  zgenom load atuinsh/atuin
  zgenom load zpm-zsh/undollar
  zgenom load totoroot/kube-ps1
  [ -z "$SSH_CONNECTION" ] && zgenom load totoroot/fast-syntax-highlighting
  zgenom save
fi

source $ZDOTDIR/config.zsh
if [[ $TERM != dumb ]]; then
  source $ZDOTDIR/keybinds.zsh
  source $ZDOTDIR/completion.zsh
  source $ZDOTDIR/aliases.zsh
  source $ZDOTDIR/extract.zsh
  source $ZDOTDIR/prompt.zsh

  function _cache {
    command -v "$1" >/dev/null || return 1
    local cache_dir="$XDG_CACHE_HOME/${SHELL##*/}"
    local cache="$cache_dir/$1"
    if [[ ! -f $cache || ! -s $cache ]]; then
      echo "Caching $1"
      mkdir -p $cache_dir
      "$@" >$cache
    fi
    source $cache || rm -f $cache
  }

  # Use fd instead of find if installed
  if command -v fd >/dev/null; then
    export FZF_DEFAULT_COMMAND="fd ."
    export FZF_CTRL_H_COMMAND="fd -t d . $HOME"
  fi

  if command -v zoxide >/dev/null; then
    eval "$(zoxide init zsh --cmd cd)"
  fi

  # if command -v kube_ps1 >/dev/null; then
  #   export RPROMPT='$(kube_ps1)'$RPROMPT
  #   zle -N kubetoggle
  #   bindkey '^K' kubetoggle
  # fi

  ## Auto-generated by my Nix config
  source $ZDOTDIR/extra.zshrc

  autoload -Uz compinit && compinit -u -d $ZSH_CACHE/zcompdump
  autopair-init

  # If you have host-local configuration, this is where you'd put it
  [ -f ~/.zshrc ] && source ~/.zshrc
fi
