## Auto-generated by my nix config
export XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"
export XDG_CACHE_HOME="${XDG_CACHE_HOME:-$HOME/.cache}"
export XDG_DATA_HOME="${XDG_DATA_HOME:-$HOME/.local/share}"
export XDG_STATE_HOME="${XDG_STATE_HOME:-$HOME/.local/state}"

export ZDOTDIR="${ZDOTDIR:-$XDG_CONFIG_HOME/zsh}"
export ZSH_CACHE="${ZSH_CACHE:-$XDG_CACHE_HOME/zsh}"
export ZGENOM_DIR="${ZGENOM_DIR:-$XDG_DATA_HOME/zsh}"
export ZGENOM_SOURCE="${ZGENOM_SOURCE:-$ZGENOM_DIR/zgenom.zsh}"

[ -f "${0:a:h}/extra.zshenv" ] && source "${0:a:h}/extra.zshenv"

# If you have host-local configuration, this is where you'd put it
[ -f ~/.zshenv ] && source ~/.zshenv
