#!/usr/bin/env sh

bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_follows_pointer true

bspc config border_width 10
bspc config window_gap 20

bspc config normal_border_color "#181a23"
bspc config active_border_color "#181a23"
bspc config focused_border_color "#bd93f9"
bspc config presel_feedback_color "#bd93f9"

# Extra padding for polybar
bspc config -m primary top_padding 52
bspc config -m primary bottom_padding 0
