{
 "title": "Home Assistant",
 "description": "Keep track of sensor states, switches etc. added to Home Assistant with this dashboard",
 "tags": [
  "home-assistant",
  "sensors",
  "automation"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  { "title": "Motion", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Motion Sensors",
   "type": "state-timeline",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "homeassistant_binary_sensor_state{friendly_name=~\".*Motion.*\"}",
     "legendFormat": "{{friendly_name}}"
    }
   ]
  },
  {
   "title": "Doors",
   "type": "state-timeline",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "homeassistant_binary_sensor_state{friendly_name=~\".*Door.*\"}",
     "legendFormat": "{{friendly_name}}"
    }
   ]
  },
  { "title": "Air Quality", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Air Quality",
   "type": "timeseries",
   "description": "2.5µm particulate matter concentration as a measure of air quality",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "homeassistant_sensor_pm25_u0xb5g_per_mu0xb3",
     "legendFormat": "{{friendly_name}}"
    }
   ]
  },
  { "title": "Power", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Power Consumption in kWh",
   "type": "stat",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "homeassistant_sensor_energy_kwh",
     "legendFormat": "{{friendly_name}}"
    }
   ]
  },
  {
   "title": "Power Consumption Power Plugs",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 29 },
   "targets": [
    { "expr": "homeassistant_sensor_power_w", "legendFormat": "{{friendly_name}}" }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Switches",
   "type": "state-timeline",
   "gridPos": { "h": 9, "w": 18, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "homeassistant_switch_state{friendly_name=~\".*Switch\"}",
     "legendFormat": "{{friendly_name}}"
    }
   ]
  },
  {
   "title": "Brightness Level Light",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 45 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "homeassistant_light_brightness_percent",
     "legendFormat": "{{friendly_name}}"
    }
   ]
  },
  {
   "title": "Battery Levels",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (friendly_name) (homeassistant_sensor_battery_percent{friendly_name!=\"FP5 Battery level\"})",
     "legendFormat": "{{friendly_name}}"
    }
   ]
  }
 ]
}