{
 "title": "Postfix Delivery Status",
 "description": "Log-based solution for monitoring Postfix",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Total reasons",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (status) (count_over_time({job=\"systemd-journal\",host=\"$host\"} |= \"postfix/smtp\" |= \" status=\" | regexp \"status=(?P<status>[a-z]+)\" | status != \"\" | status != \"deferred\" [$__range]))"
    }
   ]
  },
  {
   "title": "Delivered by domains",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "topk(25, sum by (domain) (count_over_time({job=\"systemd-journal\",host=\"$host\"} |= \" status=sent \" | regexp \"to=<[^@>]+@(?P<domain>[^>]+)>\" [$__range])))"
    }
   ]
  },
  {
   "title": "Bounced by domains",
   "type": "table",
   "gridPos": { "h": 8, "w": 5, "x": 14, "y": 0 },
   "targets": [
    {
     "expr": "topk(25, sum by (domain) (count_over_time({job=\"systemd-journal\",host=\"$host\"} |= \" status=bounced \" | regexp \"to=<[^@>]+@(?P<domain>[^>]+)>\" [$__range])))"
    }
   ]
  },
  {
   "title": "Delivery Status Notification",
   "type": "table",
   "gridPos": { "h": 18, "w": 5, "x": 19, "y": 0 },
   "targets": [
    {
     "expr": "topk(100, sum by (dsn,status) (count_over_time({job=\"systemd-journal\",host=\"$host\"} |= \" dsn=\" |= \" status=\" | regexp \"dsn=(?P<dsn>[^,]+), status=(?P<status>[a-z]+)\" [$__range])))"
    }
   ]
  },
  {
   "title": "Mail events rate",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 19, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (status) (count_over_time({job=\"systemd-journal\",host=\"$host\"} |= \"postfix/smtp\" |= \" status=\" | regexp \"status=(?P<status>[a-z]+)\" | status != \"\" [5m]))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Unique recipients",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 19, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "sum by (status) (count_over_time({job=\"systemd-journal\",host=\"$host\"} |= \"postfix/smtp\" |= \" status=\" | regexp \"status=(?P<status>[a-z]+)\" | status != \"\" | status != \"deferred\" [5m]))",
     "legendFormat": "{{status}}"
    }
   ]
  }
 ]
}