{
 "title": "S.M.A.R.T.",
 "description": "Metrics exposed by the official Prometheus smartctl_exporter (https://github.com/prometheus-community/smartctl_exporter)",
 "tags": [
  "disks",
  "smart",
  "smartctl"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(smartctl_version,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "S.M.A.R.T. Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "smartctl_device_smart_status{instance=~\"$instance\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "smartctl_device_temperature{instance=~\"$instance\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Device Critical Warning",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "smartctl_device_critical_warning{instance=~\"$instance\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Error Log Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "smartctl_device_error_log_count{instance=~\"$instance\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Device Media Error",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "smartctl_device_media_errors{instance=~\"$instance\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Power on Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "smartctl_device_power_on_seconds{instance=~\"$instance\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Power Cycle",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "smartctl_device_power_cycle_count{instance=~\"$instance\"}",
     "legendFormat": "{{device}}"
    }
   ]
  }
 ]
}