{
 "title": "SSH Tarpit",
 "description": "Dashboard for SSH tarpit/honeypot with endlessh-go",
 "tags": [
  "prometheus",
  "ssh",
  "endlessh",
  "tarpit",
  "honeypot"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(endlessh_client_open_count_total, job)"
    }
   },
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values(endlessh_client_open_count_total{job=~\"$job\"}, instance)"
    }
   },
   {
    "name": "port",
    "label": "Port",
    "query": {
     "query": "label_values(endlessh_client_open_count_total{job=~\"$job\", instance=~\"$host\"},local_port)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Connections",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(endlessh_client_open_count{instance=~\"$host\", local_port=~\"$port\",job=~\"$job\"} - endlessh_client_open_count{instance=~\"$host\",local_port=~\"$port\",job=~\"$job\"} offset $__interval) > 0 or (endlessh_client_open_count{instance=~\"$host\",local_port=~\"$port\",job=~\"$job\"}!=0 unless endlessh_client_open_count{instance=~\"$host\",local_port=~\"$port\",job=~\"$job\"} offset $__interval)",
     "legendFormat": "Seen {{ip}}"
    },
    {
     "expr": "(endlessh_client_trapped_time_seconds{instance=~\"$host\",local_port=~\"$port\",job=~\"$job\"} - endlessh_client_trapped_time_seconds{instance=~\"$host\",local_port=~\"$port\",job=~\"$job\"} offset $__interval) > 0 or (endlessh_client_trapped_time_seconds{instance=~\"$host\",local_port=~\"$port\",job=~\"$job\"}!=0 unless endlessh_client_trapped_time_seconds{instance=~\"$host\",local_port=~\"$port\",job=~\"$job\"} offset $__interval)",
     "legendFormat": "Trapped {{ip}}"
    }
   ]
  },
  {
   "title": "Trapped Time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 36 }
   ]
  },
  {
   "title": "Sent Bytes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(endlessh_sent_bytes_total{instance=~\"$host\",local_port=~\"$port\",job=~\"$job\"}[$__range]))",
     "legendFormat": "Bytes sent by endlessh"
    }
   ]
  },
  {
   "title": "Unique IPs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 36 }
   ]
  },
  {
   "title": "Latest Connection",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 36 }
   ]
  },
  {
   "title": "Current Connections",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum((endlessh_client_open_count_total{instance=~\"$host\",local_port=~\"$port\",job=~\"$job\"}) - (endlessh_client_closed_count_total{instance=~\"$host\",local_port=~\"$port\",job=~\"$job\"} or endlessh_client_open_count_total{instance=~\"$host\",local_port=~\"$port\",job=~\"$job\"} * 0))",
     "legendFormat": "Open Connections"
    }
   ]
  },
  {
   "title": "Concurrent Connections",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "sum((endlessh_client_open_count_total{instance=~\"$host\",local_port=~\"$port\",job=~\"$job\"}) - (endlessh_client_closed_count_total{instance=~\"$host\",local_port=~\"$port\",job=~\"$job\"} or\n endlessh_client_open_count_total{instance=~\"$host\",local_port=~\"$port\",job=~\"$job\"} * 0))",
     "legendFormat": "Open Connections"
    }
   ]
  },
  {
   "title": "Connections by Country",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 36 }
   ]
  },
  {
   "title": "Maximum desperation",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    { "panelId": 36 }
   ]
  },
  {
   "title": "Clients",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 11 },
   "targets": [
    { "panelId": 36 }
   ]
  },
  {
   "title": "Locations",
   "type": "geomap",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 11 },
   "targets": [
    { "panelId": 36 }
   ]
  }
 ]
}