# modules/hardware/fancontrol.nix

{ options, config, lib, pkgs, ... }:

with lib;
with lib.my;
let cfg = config.modules.hardware.fancontrol;
in {
  options.modules.hardware.fancontrol = {
    enable = mkBoolOpt false;
  };

  config = mkIf cfg.enable {
    hardware.fancontrol.enable = true;
    hardware.fancontrol.config = ''
      # Configuration file generated by pwmconfig
      INTERVAL=10
      DEVPATH=hwmon0=devices/platform/it87.656
      DEVNAME=hwmon0=it8721
      FCTEMPS=hwmon0/pwm3=hwmon0/temp1_input hwmon0/pwm1=hwmon0/temp1_input
      FCFANS=hwmon0/pwm3=hwmon0/fan3_input+hwmon0/fan2_input hwmon0/pwm1=hwmon0/fan1_input
      MINTEMP=hwmon0/pwm3=30 hwmon0/pwm1=30
      MAXTEMP=hwmon0/pwm3=60 hwmon0/pwm1=60
      MINSTART=hwmon0/pwm3=150 hwmon0/pwm1=150
      MINSTOP=hwmon0/pwm3=100 hwmon0/pwm1=100
      '';
  };
}
