# modules/hardware/fancontrol.nix

{ options, config, lib, ... }:

with lib;
with lib.my;
let cfg = config.modules.hardware.fancontrol;
in {
  options.modules.hardware.fancontrol = {
    enable = mkBoolOpt false;
  };

  config = mkIf cfg.enable {
    hardware.fancontrol.enable = false;
    # hardware.fancontrol.config = ''
    # # Configuration file generated by pwmconfig
    # INTERVAL=10
    # DEVPATH=
    # DEVNAME=
    # FCTEMPS=
    # FCFANS=
    # MINTEMP=
    # MAXTEMP=
    # MINSTART=
    # MINSTOP=
    # '';
  };
}
